/**
 * OG image for /contributor/<handle>.
 *
 * Renders a 1200x630 PNG with the contributor's name, handle, archetype,
 * and top-pillar caption — branded in cream + brass + Cormorant Garamond
 * + DM Mono.
 *
 * Three faces:
 *   - Cormorant Garamond Medium Italic — display name, archetype, wordmark
 *   - Cormorant Garamond Medium        — fallback for non-italic display
 *   - DM Mono Medium                   — handle, pillar caption, glyph
 *
 * Defensive: any failure falls back to a brand card. Never 500s the route.
 *
 * Font loading: Node.js runtime + readFile from /assets/fonts/. The TTFs
 * MUST live outside the dynamic [handle] segment — Next.js file-tracing
 * does not include sibling assets of dynamic-route files in the function
 * bundle (vercel/next.js#48081). We force inclusion via
 * `outputFileTracingIncludes` in next.config.mjs.
 *
 * History of failed approaches before this one:
 *   1. `new URL('./X.ttf', import.meta.url)` (Node)  — Node fetch can't
 *      open file:// URLs.
 *   2. Same pattern in Edge runtime                  — file not in bundle
 *      because [handle] segment defeats tracing.
 *   3. jsDelivr `cdn.jsdelivr.net/gh/google/fonts`   — 403 rate-limited.
 *   4. raw.githubusercontent.com                     — 403 from Vercel
 *      Edge regions.
 * Lesson: external CDNs are nondeterministic for production OG cards.
 * Ship the fonts WITH the deployment, period.
 */

import { ImageResponse } from 'next/og';
import { readFile, readdir } from 'node:fs/promises';
import { join } from 'node:path';
import { getProfileByHandle } from '@/lib/get-profile';

// Node.js runtime is the canonical home for OG image generation in
// Next.js 15+ when assets are bundled with the deployment. Edge had
// faster cold starts but couldn't reliably read local files when the
// route lives behind a dynamic segment.
export const runtime = 'nodejs';

export const size = { width: 1200, height: 630 };
export const contentType = 'image/png';

const T = {
  cream:      '#f7f2e8',
  paper:      '#fefcf5',
  ink:        '#2c2620',
  body:       '#3a342c',
  soft:       '#5a5248',
  tertiary:   '#8c8780',
  brassDeep:  '#7a4a10',
  brassMid:   '#b8862e',
  brassPale:  '#f5dfa0',
  border:     '#e0dbd2',
};

const PILLAR_LABELS = {
  acuity:      'Acuity',
  calibration: 'Calibration',
  magnanimity: 'Magnanimity',
  discourse:   'Discourse',
  consistency: 'Consistency',
  reach:       'Reach',
};

// ─── Helpers ─────────────────────────────────────────────────────────────

function topTwoPillars(axisScores) {
  if (!axisScores) return null;
  const sorted = Object.entries(PILLAR_LABELS)
    .map(([k, label]) => ({ label, score: axisScores[k] || 0 }))
    .filter((p) => p.score > 0)
    .sort((a, b) => b.score - a.score);
  if (sorted.length < 2) return null;
  return [sorted[0].label, sorted[1].label];
}

function initialsOf(name) {
  if (!name) return '?';
  return (
    name
      .split(/\s+/)
      .filter(Boolean)
      .slice(0, 2)
      .map((w) => (w[0] || '').toUpperCase())
      .join('') || '?'
  );
}

// Read a font file from /assets/fonts/ at the project root.
//
// The folder is bundled into the serverless function via
// `outputFileTracingIncludes` in next.config.mjs (the [handle] dynamic
// segment defeats Next.js's automatic asset tracing — see header).
//
// Return the raw Node.js Buffer. Satori (the underlying renderer for
// @vercel/og) expects either a Uint8Array or a Buffer — it inspects
// the first 4 bytes for the OpenType signature using Uint8Array
// semantics. Converting to a plain ArrayBuffer (e.g. via
// `buffer.buffer.slice(...)`) trips a `Unsupported OpenType signature`
// error even though the bytes are identical, because the parser
// reads through different views of memory.
//
// On read failure, the thrown error carries the resolved path, the
// cwd, and the actual directory contents — so a runtime log line
// tells us exactly what tracing did and didn't pull in.
async function loadFont(filename) {
  const path = join(process.cwd(), 'assets', 'fonts', filename);
  try {
    return await readFile(path);
  } catch (err) {
    const cwd = process.cwd();
    let dirContents;
    try {
      dirContents = await readdir(join(cwd, 'assets', 'fonts'));
    } catch (e) {
      dirContents = `[readdir failed: ${e.code || e.message}]`;
    }
    throw new Error(
      `loadFont(${filename}) at ${path} failed: ${err.code || err.message} | cwd=${cwd} | dir=${JSON.stringify(dirContents)}`
    );
  }
}

// Render an ImageResponse to a buffered PNG response. This is the
// LOAD-BEARING fix for FUNCTION_INVOCATION_FAILED with no logs:
// `new ImageResponse(...)` returns a streaming Response whose body is
// generated by Satori AFTER we return. If Satori throws during stream
// generation, our outer try/catch can't see it — Vercel reports a
// generic 500 with no error message.
//
// By awaiting `.arrayBuffer()` we force the stream to drain inside
// the calling try/catch, so any Satori error surfaces synchronously
// with a useful message.
async function renderImage(jsx, options) {
  const streaming = new ImageResponse(jsx, options);
  const buffer = await streaming.arrayBuffer();
  return new Response(buffer, {
    status: 200,
    headers: {
      'Content-Type': 'image/png',
      'Cache-Control': 'public, immutable, no-transform, max-age=31536000',
    },
  });
}

// Diagnostic probe — hit /contributor/_probe/opengraph-image to get
// JSON describing the runtime environment instead of a PNG. Lets us
// see exactly where Node is looking and what tracing actually
// bundled, without depending on stderr being captured.
async function probeResponse() {
  const cwd = process.cwd();
  const fontsDir = join(cwd, 'assets', 'fonts');
  let dirContents = null;
  let dirErr = null;
  try {
    dirContents = await readdir(fontsDir);
  } catch (e) {
    dirErr = e.code || e.message;
  }
  let fontReadStatus = null;
  try {
    const buf = await readFile(join(fontsDir, 'CormorantGaramond-MediumItalic.ttf'));
    const hex = Array.from(buf.subarray(0, 4)).map((b) => b.toString(16).padStart(2, '0')).join(' ');
    fontReadStatus = `ok: ${buf.byteLength} bytes, magic=${hex}`;
  } catch (e) {
    fontReadStatus = `fail: ${e.code || e.message}`;
  }
  return Response.json({
    cwd,
    fontsDir,
    dirContents,
    dirErr,
    fontReadStatus,
    nodeVersion: process.version,
    arch: process.arch,
    platform: process.platform,
  });
}

// Brand-only fallback card. Two variants:
//   - Fonts loaded:   full branded layout with italic ⁂ glyph.
//   - Fonts missing:  plain non-italic text. Satori's built-in
//                     fallback font has no italic face, so referencing
//                     `fontStyle: 'italic'` without a loaded italic
//                     font crashes the renderer synchronously
//                     ("Cannot read properties of undefined (reading
//                     'split')"). The plain variant guarantees we
//                     never propagate that crash to the client.
async function brandCard(fonts, fontsLoaded) {
  if (!fontsLoaded) {
    return await renderImage(
      (
        <div
          style={{
            width: '100%',
            height: '100%',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            background: T.cream,
            color: T.brassDeep,
            fontSize: 96,
            letterSpacing: '0.4em',
          }}>
          DIALECTA
        </div>
      ),
      size
    );
  }
  return await renderImage(
    (
      <div
        style={{
          width: '100%',
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          background: T.cream,
        }}>
        <div style={{
          fontFamily: 'DM Mono',
          fontSize: 32,
          color: T.brassMid,
          letterSpacing: '0.5em',
          marginBottom: 16,
        }}>
          DIALECTA
        </div>
        <div style={{
          fontFamily: 'Cormorant Garamond',
          fontStyle: 'italic',
          fontSize: 96,
          color: T.brassDeep,
        }}>
          ⁂
        </div>
      </div>
    ),
    { ...size, fonts }
  );
}

// ─── Image render ────────────────────────────────────────────────────────

export default async function Image({ params }) {
  const { handle } = await params;

  // Diagnostic probe — see header comment on `probeResponse`.
  if (handle === '_probe') return await probeResponse();

  // Load fonts (in parallel, with fallback to no-fonts on any failure)
  let fonts = [];
  let fontsLoaded = false;
  try {
    // All three faces are static-weight TTFs.
    //
    // The Cormorant Garamond TTFs were obtained from the Google Fonts
    // CSS API (fonts.googleapis.com/css) using an Android-era User-Agent
    // — that path returns latin-subset *static* TTFs (76 KB / 79 KB).
    // The same API with a modern Chrome UA returns WOFF2, which the
    // Node.js build of @vercel/og does not decode (it lacks the wasm
    // decoder that the Edge build bundles). The GitHub fonts repo
    // only ships variable fonts for this family.
    //
    // DM Mono is still shipped as a static-weight TTF in the GitHub
    // repo, so we use that source for it.
    const [italic, roman, mono] = await Promise.all([
      loadFont('CormorantGaramond-MediumItalic.ttf'),
      loadFont('CormorantGaramond-Medium.ttf'),
      loadFont('DMMono-Medium.ttf'),
    ]);
    fonts = [
      { name: 'Cormorant Garamond', data: italic, style: 'italic', weight: 500 },
      { name: 'Cormorant Garamond', data: roman,  style: 'normal', weight: 500 },
      { name: 'DM Mono',             data: mono,   style: 'normal', weight: 500 },
    ];
    fontsLoaded = true;
  } catch (err) {
    console.error('[og-image] font load failed; rendering with default font:', err?.message);
  }

  // Helper: only emit a fontFamily prop when the matching font is loaded.
  // Without this guard, fontFamily references for unloaded fonts make
  // Satori throw, which would 500 the route even with our other guards.
  const ff = (family) => (fontsLoaded ? family : undefined);

  // Fetch profile (with fallback)
  let data = null;
  try {
    data = await getProfileByHandle(handle);
  } catch (err) {
    console.error('[og-image] getProfileByHandle failed:', err?.message);
  }

  // Helper: every brandCard call needs the same exception net. If
  // brandCard itself crashes (Satori choking on a font edge case),
  // we return a clean text 500 instead of an unhandled exception.
  const safeBrand = async (renderErrMsg) => {
    try {
      return await brandCard(fonts, fontsLoaded);
    } catch (brandErr) {
      console.error('[og-image] brandCard failed:', brandErr?.message);
      return new Response(
        `OG generation failed.\n\nrender: ${renderErrMsg || '(profile missing)'}\nbrand: ${brandErr?.message}`,
        { status: 500, headers: { 'Content-Type': 'text/plain' } }
      );
    }
  };

  if (!data) return await safeBrand(null);

  try {
    const name           = data.display_name || 'Contributor';
    const archetypeLabel = data.archetype?.label || 'Pattern Still Forming';
    const tp             = topTwoPillars(data.axisScores);
    const pillarCaption  = tp ? `Strong on ${tp[0]} and ${tp[1]}` : 'Pattern still forming';
    const handleDisplay  = data.handle ? '@' + data.handle : '';
    const initials       = initialsOf(name);

    return await renderImage(
      (
        <div
          style={{
            width: '100%',
            height: '100%',
            display: 'flex',
            flexDirection: 'column',
            background: T.cream,
            padding: 64,
          }}>
          {/* Brand bar */}
          <div style={{
            display: 'flex',
            alignItems: 'center',
            color: T.brassDeep,
          }}>
            <div style={{
              fontFamily: ff('DM Mono'),
              fontSize: 22,
              color: T.brassMid,
              letterSpacing: '0.4em',
              marginRight: 12,
            }}>⁂</div>
            <div style={{
              fontFamily: ff('Cormorant Garamond'),
              fontStyle: 'italic',
              fontSize: 30,
            }}>Dialecta</div>
          </div>

          {/* Body */}
          <div style={{
            display: 'flex',
            flex: 1,
            alignItems: 'center',
            marginTop: 24,
          }}>
            {/* Avatar disc with initials */}
            <div style={{
              width: 280,
              height: 280,
              borderRadius: 9999,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              flexShrink: 0,
              background: T.paper,
              border: `6px solid ${T.brassMid}`,
              marginRight: 56,
            }}>
              <div style={{
                fontFamily: ff('Cormorant Garamond'),
                fontStyle: 'italic',
                fontSize: 130,
                color: T.brassMid,
              }}>
                {initials}
              </div>
            </div>

            {/* Identity */}
            <div style={{ display: 'flex', flexDirection: 'column', flex: 1 }}>
              <div style={{
                fontFamily: ff('Cormorant Garamond'),
                fontStyle: 'italic',
                fontSize: 76,
                color: T.brassDeep,
                lineHeight: 1.05,
                marginBottom: 12,
              }}>
                {name}
              </div>

              {handleDisplay && (
                <div style={{
                  fontFamily: ff('DM Mono'),
                  fontSize: 24,
                  color: T.tertiary,
                  letterSpacing: '0.04em',
                  marginBottom: 28,
                }}>
                  {handleDisplay}
                </div>
              )}

              <div style={{
                fontFamily: ff('Cormorant Garamond'),
                fontStyle: 'italic',
                fontSize: 42,
                color: T.brassMid,
                marginBottom: 8,
              }}>
                {archetypeLabel}
              </div>

              <div style={{
                fontFamily: ff('DM Mono'),
                fontSize: 18,
                color: T.soft,
                letterSpacing: '0.16em',
                marginTop: 14,
              }}>
                {pillarCaption.toUpperCase()}
              </div>
            </div>
          </div>
        </div>
      ),
      { ...size, fonts }
    );
  } catch (err) {
    console.error('[og-image] render failed:', err?.message);
    return await safeBrand(err?.message);
  }
}
